auto_add = false
format = "UseEmoji"
signed = false
scope = false
update_url = "https://gitmoji.dev/api/gitmojis"
last_update = "+002023-06-22T15:36:16.408764051Z"

[[gitmojis]]
emoji = "ğŸ¨"
code = ":art:"
name = "art"
description = "Improve structure / format of the code."

[[gitmojis]]
emoji = "âš¡ï¸"
code = ":zap:"
name = "zap"
description = "Improve performance."

[[gitmojis]]
emoji = "ğŸ”¥"
code = ":fire:"
name = "fire"
description = "Remove code or files."

[[gitmojis]]
emoji = "ğŸ›"
code = ":bug:"
name = "bug"
description = "Fix a bug."

[[gitmojis]]
emoji = "ğŸš‘ï¸"
code = ":ambulance:"
name = "ambulance"
description = "Critical hotfix."

[[gitmojis]]
emoji = "âœ¨"
code = ":sparkles:"
name = "sparkles"
description = "Introduce new features."

[[gitmojis]]
emoji = "ğŸ“"
code = ":memo:"
name = "memo"
description = "Add or update documentation."

[[gitmojis]]
emoji = "ğŸš€"
code = ":rocket:"
name = "rocket"
description = "Deploy stuff."

[[gitmojis]]
emoji = "ğŸ’„"
code = ":lipstick:"
name = "lipstick"
description = "Add or update the UI and style files."

[[gitmojis]]
emoji = "ğŸ‰"
code = ":tada:"
name = "tada"
description = "Begin a project."

[[gitmojis]]
emoji = "âœ…"
code = ":white_check_mark:"
name = "white-check-mark"
description = "Add, update, or pass tests."

[[gitmojis]]
emoji = "ğŸ”’ï¸"
code = ":lock:"
name = "lock"
description = "Fix security issues."

[[gitmojis]]
emoji = "ğŸ”"
code = ":closed_lock_with_key:"
name = "closed-lock-with-key"
description = "Add or update secrets."

[[gitmojis]]
emoji = "ğŸ”–"
code = ":bookmark:"
name = "bookmark"
description = "Release / Version tags."

[[gitmojis]]
emoji = "ğŸš¨"
code = ":rotating_light:"
name = "rotating-light"
description = "Fix compiler / linter warnings."

[[gitmojis]]
emoji = "ğŸš§"
code = ":construction:"
name = "construction"
description = "Work in progress."

[[gitmojis]]
emoji = "ğŸ’š"
code = ":green_heart:"
name = "green-heart"
description = "Fix CI Build."

[[gitmojis]]
emoji = "â¬‡ï¸"
code = ":arrow_down:"
name = "arrow-down"
description = "Downgrade dependencies."

[[gitmojis]]
emoji = "â¬†ï¸"
code = ":arrow_up:"
name = "arrow-up"
description = "Upgrade dependencies."

[[gitmojis]]
emoji = "ğŸ“Œ"
code = ":pushpin:"
name = "pushpin"
description = "Pin dependencies to specific versions."

[[gitmojis]]
emoji = "ğŸ‘·"
code = ":construction_worker:"
name = "construction-worker"
description = "Add or update CI build system."

[[gitmojis]]
emoji = "ğŸ“ˆ"
code = ":chart_with_upwards_trend:"
name = "chart-with-upwards-trend"
description = "Add or update analytics or track code."

[[gitmojis]]
emoji = "â™»ï¸"
code = ":recycle:"
name = "recycle"
description = "Refactor code."

[[gitmojis]]
emoji = "â•"
code = ":heavy_plus_sign:"
name = "heavy-plus-sign"
description = "Add a dependency."

[[gitmojis]]
emoji = "â–"
code = ":heavy_minus_sign:"
name = "heavy-minus-sign"
description = "Remove a dependency."

[[gitmojis]]
emoji = "ğŸ”§"
code = ":wrench:"
name = "wrench"
description = "Add or update configuration files."

[[gitmojis]]
emoji = "ğŸ”¨"
code = ":hammer:"
name = "hammer"
description = "Add or update development scripts."

[[gitmojis]]
emoji = "ğŸŒ"
code = ":globe_with_meridians:"
name = "globe-with-meridians"
description = "Internationalization and localization."

[[gitmojis]]
emoji = "âœï¸"
code = ":pencil2:"
name = "pencil2"
description = "Fix typos."

[[gitmojis]]
emoji = "ğŸ’©"
code = ":poop:"
name = "poop"
description = "Write bad code that needs to be improved."

[[gitmojis]]
emoji = "âªï¸"
code = ":rewind:"
name = "rewind"
description = "Revert changes."

[[gitmojis]]
emoji = "ğŸ”€"
code = ":twisted_rightwards_arrows:"
name = "twisted-rightwards-arrows"
description = "Merge branches."

[[gitmojis]]
emoji = "ğŸ“¦ï¸"
code = ":package:"
name = "package"
description = "Add or update compiled files or packages."

[[gitmojis]]
emoji = "ğŸ‘½ï¸"
code = ":alien:"
name = "alien"
description = "Update code due to external API changes."

[[gitmojis]]
emoji = "ğŸšš"
code = ":truck:"
name = "truck"
description = "Move or rename resources (e.g.: files, paths, routes)."

[[gitmojis]]
emoji = "ğŸ“„"
code = ":page_facing_up:"
name = "page-facing-up"
description = "Add or update license."

[[gitmojis]]
emoji = "ğŸ’¥"
code = ":boom:"
name = "boom"
description = "Introduce breaking changes."

[[gitmojis]]
emoji = "ğŸ±"
code = ":bento:"
name = "bento"
description = "Add or update assets."

[[gitmojis]]
emoji = "â™¿ï¸"
code = ":wheelchair:"
name = "wheelchair"
description = "Improve accessibility."

[[gitmojis]]
emoji = "ğŸ’¡"
code = ":bulb:"
name = "bulb"
description = "Add or update comments in source code."

[[gitmojis]]
emoji = "ğŸ»"
code = ":beers:"
name = "beers"
description = "Write code drunkenly."

[[gitmojis]]
emoji = "ğŸ’¬"
code = ":speech_balloon:"
name = "speech-balloon"
description = "Add or update text and literals."

[[gitmojis]]
emoji = "ğŸ—ƒï¸"
code = ":card_file_box:"
name = "card-file-box"
description = "Perform database related changes."

[[gitmojis]]
emoji = "ğŸ”Š"
code = ":loud_sound:"
name = "loud-sound"
description = "Add or update logs."

[[gitmojis]]
emoji = "ğŸ”‡"
code = ":mute:"
name = "mute"
description = "Remove logs."

[[gitmojis]]
emoji = "ğŸ‘¥"
code = ":busts_in_silhouette:"
name = "busts-in-silhouette"
description = "Add or update contributor(s)."

[[gitmojis]]
emoji = "ğŸš¸"
code = ":children_crossing:"
name = "children-crossing"
description = "Improve user experience / usability."

[[gitmojis]]
emoji = "ğŸ—ï¸"
code = ":building_construction:"
name = "building-construction"
description = "Make architectural changes."

[[gitmojis]]
emoji = "ğŸ“±"
code = ":iphone:"
name = "iphone"
description = "Work on responsive design."

[[gitmojis]]
emoji = "ğŸ¤¡"
code = ":clown_face:"
name = "clown-face"
description = "Mock things."

[[gitmojis]]
emoji = "ğŸ¥š"
code = ":egg:"
name = "egg"
description = "Add or update an easter egg."

[[gitmojis]]
emoji = "ğŸ™ˆ"
code = ":see_no_evil:"
name = "see-no-evil"
description = "Add or update a .gitignore file."

[[gitmojis]]
emoji = "ğŸ“¸"
code = ":camera_flash:"
name = "camera-flash"
description = "Add or update snapshots."

[[gitmojis]]
emoji = "âš—ï¸"
code = ":alembic:"
name = "alembic"
description = "Perform experiments."

[[gitmojis]]
emoji = "ğŸ”ï¸"
code = ":mag:"
name = "mag"
description = "Improve SEO."

[[gitmojis]]
emoji = "ğŸ·ï¸"
code = ":label:"
name = "label"
description = "Add or update types."

[[gitmojis]]
emoji = "ğŸŒ±"
code = ":seedling:"
name = "seedling"
description = "Add or update seed files."

[[gitmojis]]
emoji = "ğŸš©"
code = ":triangular_flag_on_post:"
name = "triangular-flag-on-post"
description = "Add, update, or remove feature flags."

[[gitmojis]]
emoji = "ğŸ¥…"
code = ":goal_net:"
name = "goal-net"
description = "Catch errors."

[[gitmojis]]
emoji = "ğŸ’«"
code = ":dizzy:"
name = "animation"
description = "Add or update animations and transitions."

[[gitmojis]]
emoji = "ğŸ—‘ï¸"
code = ":wastebasket:"
name = "wastebasket"
description = "Deprecate code that needs to be cleaned up."

[[gitmojis]]
emoji = "ğŸ›‚"
code = ":passport_control:"
name = "passport-control"
description = "Work on code related to authorization, roles and permissions."

[[gitmojis]]
emoji = "ğŸ©¹"
code = ":adhesive_bandage:"
name = "adhesive-bandage"
description = "Simple fix for a non-critical issue."

[[gitmojis]]
emoji = "ğŸ§"
code = ":monocle_face:"
name = "monocle-face"
description = "Data exploration/inspection."

[[gitmojis]]
emoji = "âš°ï¸"
code = ":coffin:"
name = "coffin"
description = "Remove dead code."

[[gitmojis]]
emoji = "ğŸ§ª"
code = ":test_tube:"
name = "test-tube"
description = "Add a failing test."

[[gitmojis]]
emoji = "ğŸ‘”"
code = ":necktie:"
name = "necktie"
description = "Add or update business logic."

[[gitmojis]]
emoji = "ğŸ©º"
code = ":stethoscope:"
name = "stethoscope"
description = "Add or update healthcheck."

[[gitmojis]]
emoji = "ğŸ§±"
code = ":bricks:"
name = "bricks"
description = "Infrastructure related changes."

[[gitmojis]]
emoji = "ğŸ§‘â€ğŸ’»"
code = ":technologist:"
name = "technologist"
description = "Improve developer experience."

[[gitmojis]]
emoji = "ğŸ’¸"
code = ":money_with_wings:"
name = "money-with-wings"
description = "Add sponsorships or money related infrastructure."

[[gitmojis]]
emoji = "ğŸ§µ"
code = ":thread:"
name = "thread"
description = "Add or update code related to multithreading or concurrency."

[[gitmojis]]
emoji = "ğŸ¦º"
code = ":safety_vest:"
name = "safety-vest"
description = "Add or update code related to validation."
